/*
 * 版权所有 (c) 2015 。 李倍存 （iPso）。
 * 所有者对该文件所包含的代码的正确性、执行效率等任何方面不作任何保证。
 * 所有个人和组织均可不受约束地将该文件所包含的代码用于非商业用途。若需要将其用于商业软件的开发，请首先联系所有者以取得许可。
 */

package loadPrediction.domain.visitors;

import  jfreechart.JFreeChartFacade;
import  loadPrediction.domain.LoadData;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

import java.awt.*;

/**
 * 李倍存 创建于 2015-03-05 20:08。电邮 1174751315@qq.com。
 */
public class LoadData2JFreeChartVisitor implements LoadDataVisitor {
    public LoadData2JFreeChartVisitor() {
    }

    @Override
    public Object visit(LoadData loadData) {
        DefaultCategoryDataset ds = new JFreeChartFacade().createDataset();
        String col = "";
//        ds.addValue(loadData.getData00,"00:00:00"()(),col);
//        ds.addValue(loadData.getData01,""()(),col);
//        ds.addValue(loadData.getData02,""()(),col);
//        ds.addValue(loadData.getData03,"00:45:00"()(),col);
//        ds.addValue(loadData.getData04,"01:00:00"()(),col);
//        ds.addValue(loadData.getData05,""()(),col);
//        ds.addValue(loadData.getData06,""()(),col);
//        ds.addValue(loadData.getData07,"01:45:00"()(),col);
//        ds.addValue(loadData.getData08,"02:00:00"()(),col);
//        ds.addValue(loadData.getData09,""()(),col);
//        ds.addValue(loadData.getData10,""()(),col);
//        ds.addValue(loadData.getData11,""()(),col);
//        ds.addValue(loadData.getData12,"03:00:00"()(),col);
//        ds.addValue(loadData.getData13,""()(),col);
//        ds.addValue(loadData.getData14,""()(),col);
//        ds.addValue(loadData.getData15,""()(),col);
//        ds.addValue(loadData.getData16,"04:00:00"()(),col);
//        ds.addValue(loadData.getData17,""()(),col);
//        ds.addValue(loadData.getData18,""()(),col);
//        ds.addValue(loadData.getData19,""()(),col);
//        ds.addValue(loadData.getData20,"05:00:00"()(),col);
//        ds.addValue(loadData.getData21,""()(),col);
//        ds.addValue(loadData.getData22,""()(),col);
//        ds.addValue(loadData.getData23,""()(),col);
//        ds.addValue(loadData.getData24,"06:00:00"()(),col);
//        ds.addValue(loadData.getData25,""()(),col);
//        ds.addValue(loadData.getData26,""()(),col);
//        ds.addValue(loadData.getData27,""()(),col);
//        ds.addValue(loadData.getData28,"07:00:00"()(),col);
//        ds.addValue(loadData.getData29,""()(),col);
//        ds.addValue(loadData.getData30,""()(),col);
//        ds.addValue(loadData.getData31,""()(),col);
//        ds.addValue(loadData.getData32,"08:00:00"()(),col);
//        ds.addValue(loadData.getData33,""()(),col);
//        ds.addValue(loadData.getData34,""()(),col);
//        ds.addValue(loadData.getData35,""()(),col);
//        ds.addValue(loadData.getData36,"09:00:00"()(),col);
//        ds.addValue(loadData.getData37,""()(),col);
//        ds.addValue(loadData.getData38,""()(),col);
//        ds.addValue(loadData.getData39,""()(),col);
//        ds.addValue(loadData.getData40,"10:00:00"()(),col);
//        ds.addValue(loadData.getData41,""()(),col);
//        ds.addValue(loadData.getData42,""()(),col);
//        ds.addValue(loadData.getData43,""()(),col);
//        ds.addValue(loadData.getData44,"11:00:00"()(),col);
//        ds.addValue(loadData.getData45,""()(),col);
//        ds.addValue(loadData.getData46,""()(),col);
//        ds.addValue(loadData.getData47,""()(),col);
//        ds.addValue(loadData.getData48,"12:00:00"()(),col);
//        ds.addValue(loadData.getData49,""()(),col);
//        ds.addValue(loadData.getData50,""()(),col);
//        ds.addValue(loadData.getData51,""()(),col);
//        ds.addValue(loadData.getData52,"13:00:00"()(),col);
//        ds.addValue(loadData.getData53,""(),col);
//        ds.addValue(loadData.getData54,""(),col);
//        ds.addValue(loadData.getData55,""(),col);
//        ds.addValue(loadData.getData56,"14:00:00"(),col);
//        ds.addValue(loadData.getData57,""(),col);
//        ds.addValue(loadData.getData58,""(),col);
//        ds.addValue(loadData.getData59,""(),col);
//        ds.addValue(loadData.getData60,"15:00:00"(),col);
//        ds.addValue(loadData.getData61,""(),col);
//        ds.addValue(loadData.getData62,""(),col);
//        ds.addValue(loadData.getData63,""(),col);
//        ds.addValue(loadData.getData64,"16:00:00"(),col);
//        ds.addValue(loadData.getData65,""(),col);
//        ds.addValue(loadData.getData66,""(),col);
//        ds.addValue(loadData.getData67,""(),col);
//        ds.addValue(loadData.getData68,"17:00:00"(),col);
//        ds.addValue(loadData.getData69,""(),col);
//        ds.addValue(loadData.getData70,""(),col);
//        ds.addValue(loadData.getData71,""(),col);
//        ds.addValue(loadData.getData72,"18:00:00"(),col);
//        ds.addValue(loadData.getData73,""(),col);
//        ds.addValue(loadData.getData74,""(),col);
//        ds.addValue(loadData.getData75,""(),col);
//        ds.addValue(loadData.getData76,"19:00:00"(),col);
//        ds.addValue(loadData.getData77,""(),col);
//        ds.addValue(loadData.getData78,""(),col);
//        ds.addValue(loadData.getData79,""(),col);
//        ds.addValue(loadData.getData80,"20:00:00"(),col);
//        ds.addValue(loadData.getData81,""(),col);
//        ds.addValue(loadData.getData82,""(),col);
//        ds.addValue(loadData.getData83,""(),col);
//        ds.addValue(loadData.getData84,"21:00:00"(),col);
//        ds.addValue(loadData.getData85,""(),col);
//        ds.addValue(loadData.getData86,""(),col);
//        ds.addValue(loadData.getData87,""(),col);
//        ds.addValue(loadData.getData88,"22:00:00"(),col);
//        ds.addValue(loadData.getData89,""(),col);
//        ds.addValue(loadData.getData90,""(),col);
//        ds.addValue(loadData.getData91,"22:45:00"(),col);
//        ds.addValue(loadData.getData92,"23:00:00"(),col);
//        ds.addValue(loadData.getData93,""(),col);
//        ds.addValue(loadData.getData94,""(),col);
//        ds.addValue(loadData.getData95,""(),col);

        LoadData lwr = loadData.multiple(0.9);
        col = new String("下包络线");
        ds.addValue(lwr.getData00(), col, "00:00:00");
        ds.addValue(lwr.getData01(), col, "");
        ds.addValue(lwr.getData02(), col, "");
        ds.addValue(lwr.getData03(), col, "");
        ds.addValue(lwr.getData04(), col, "01:00:00");
        ds.addValue(lwr.getData05(), col, "");
        ds.addValue(lwr.getData06(), col, "");
        ds.addValue(lwr.getData07(), col, "");
        ds.addValue(lwr.getData08(), col, "02:00:00");
        ds.addValue(lwr.getData09(), col, "");
        ds.addValue(lwr.getData10(), col, "");
        ds.addValue(lwr.getData11(), col, "");
        ds.addValue(lwr.getData12(), col, "03:00:00");
        ds.addValue(lwr.getData13(), col, "");
        ds.addValue(lwr.getData14(), col, "");
        ds.addValue(lwr.getData15(), col, "");
        ds.addValue(lwr.getData16(), col, "04:00:00");
        ds.addValue(lwr.getData17(), col, "");
        ds.addValue(lwr.getData18(), col, "");
        ds.addValue(lwr.getData19(), col, "");
        ds.addValue(lwr.getData20(), col, "05:00:00");
        ds.addValue(lwr.getData21(), col, "");
        ds.addValue(lwr.getData22(), col, "");
        ds.addValue(lwr.getData23(), col, "");
        ds.addValue(lwr.getData24(), col, "06:00:00");
        ds.addValue(lwr.getData25(), col, "");
        ds.addValue(lwr.getData26(), col, "");
        ds.addValue(lwr.getData27(), col, "");
        ds.addValue(lwr.getData28(), col, "07:00:00");
        ds.addValue(lwr.getData29(), col, "");
        ds.addValue(lwr.getData30(), col, "");
        ds.addValue(lwr.getData31(), col, "");
        ds.addValue(lwr.getData32(), col, "08:00:00");
        ds.addValue(lwr.getData33(), col, "");
        ds.addValue(lwr.getData34(), col, "");
        ds.addValue(lwr.getData35(), col, "");
        ds.addValue(lwr.getData36(), col, "09:00:00");
        ds.addValue(lwr.getData37(), col, "");
        ds.addValue(lwr.getData38(), col, "");
        ds.addValue(lwr.getData39(), col, "");
        ds.addValue(lwr.getData40(), col, "10:00:00");
        ds.addValue(lwr.getData41(), col, "");
        ds.addValue(lwr.getData42(), col, "");
        ds.addValue(lwr.getData43(), col, "");
        ds.addValue(lwr.getData44(), col, "11:00:00");
        ds.addValue(lwr.getData45(), col, "");
        ds.addValue(lwr.getData46(), col, "");
        ds.addValue(lwr.getData47(), col, "");
        ds.addValue(lwr.getData48(), col, "12:00:00");
        ds.addValue(lwr.getData49(), col, "");
        ds.addValue(lwr.getData50(), col, "");
        ds.addValue(lwr.getData51(), col, "");
        ds.addValue(lwr.getData52(), col, "13:00:00");
        ds.addValue(lwr.getData53(), col, "");
        ds.addValue(lwr.getData54(), col, "");
        ds.addValue(lwr.getData55(), col, "");
        ds.addValue(lwr.getData56(), col, "14:00:00");
        ds.addValue(lwr.getData57(), col, "");
        ds.addValue(lwr.getData58(), col, "");
        ds.addValue(lwr.getData59(), col, "");
        ds.addValue(lwr.getData60(), col, "15:00:00");
        ds.addValue(lwr.getData61(), col, "");
        ds.addValue(lwr.getData62(), col, "");
        ds.addValue(lwr.getData63(), col, "");
        ds.addValue(lwr.getData64(), col, "16:00:00");
        ds.addValue(lwr.getData65(), col, "");
        ds.addValue(lwr.getData66(), col, "");
        ds.addValue(lwr.getData67(), col, "");
        ds.addValue(lwr.getData68(), col, "17:00:00");
        ds.addValue(lwr.getData69(), col, "");
        ds.addValue(lwr.getData70(), col, "");
        ds.addValue(lwr.getData71(), col, "");
        ds.addValue(lwr.getData72(), col, "18:00:00");
        ds.addValue(lwr.getData73(), col, "");
        ds.addValue(lwr.getData74(), col, "");
        ds.addValue(lwr.getData75(), col, "");
        ds.addValue(lwr.getData76(), col, "19:00:00");
        ds.addValue(lwr.getData77(), col, "");
        ds.addValue(lwr.getData78(), col, "");
        ds.addValue(lwr.getData79(), col, "");
        ds.addValue(lwr.getData80(), col, "20:00:00");
        ds.addValue(lwr.getData81(), col, "");
        ds.addValue(lwr.getData82(), col, "");
        ds.addValue(lwr.getData83(), col, "");
        ds.addValue(lwr.getData84(), col, "21:00:00");
        ds.addValue(lwr.getData85(), col, "");
        ds.addValue(lwr.getData86(), col, "");
        ds.addValue(lwr.getData87(), col, "");
        ds.addValue(lwr.getData88(), col, "22:00:00");
        ds.addValue(lwr.getData89(), col, "");
        ds.addValue(lwr.getData90(), col, "");
        ds.addValue(lwr.getData91(), col, "");
        ds.addValue(lwr.getData92(), col, "23:00:00");
        ds.addValue(lwr.getData93(), col, "");
        ds.addValue(lwr.getData94(), col, "");
        ds.addValue(lwr.getData95(), col, "");


        col = new String("中间线");
        ds.addValue(loadData.getData00(), col, "00:00:00");
        ds.addValue(loadData.getData01(), col, "");
        ds.addValue(loadData.getData02(), col, "");
        ds.addValue(loadData.getData03(), col, "");
        ds.addValue(loadData.getData04(), col, "01:00:00");
        ds.addValue(loadData.getData05(), col, "");
        ds.addValue(loadData.getData06(), col, "");
        ds.addValue(loadData.getData07(), col, "");
        ds.addValue(loadData.getData08(), col, "02:00:00");
        ds.addValue(loadData.getData09(), col, "");
        ds.addValue(loadData.getData10(), col, "");
        ds.addValue(loadData.getData11(), col, "");
        ds.addValue(loadData.getData12(), col, "03:00:00");
        ds.addValue(loadData.getData13(), col, "");
        ds.addValue(loadData.getData14(), col, "");
        ds.addValue(loadData.getData15(), col, "");
        ds.addValue(loadData.getData16(), col, "04:00:00");
        ds.addValue(loadData.getData17(), col, "");
        ds.addValue(loadData.getData18(), col, "");
        ds.addValue(loadData.getData19(), col, "");
        ds.addValue(loadData.getData20(), col, "05:00:00");
        ds.addValue(loadData.getData21(), col, "");
        ds.addValue(loadData.getData22(), col, "");
        ds.addValue(loadData.getData23(), col, "");
        ds.addValue(loadData.getData24(), col, "06:00:00");
        ds.addValue(loadData.getData25(), col, "");
        ds.addValue(loadData.getData26(), col, "");
        ds.addValue(loadData.getData27(), col, "");
        ds.addValue(loadData.getData28(), col, "07:00:00");
        ds.addValue(loadData.getData29(), col, "");
        ds.addValue(loadData.getData30(), col, "");
        ds.addValue(loadData.getData31(), col, "");
        ds.addValue(loadData.getData32(), col, "08:00:00");
        ds.addValue(loadData.getData33(), col, "");
        ds.addValue(loadData.getData34(), col, "");
        ds.addValue(loadData.getData35(), col, "");
        ds.addValue(loadData.getData36(), col, "09:00:00");
        ds.addValue(loadData.getData37(), col, "");
        ds.addValue(loadData.getData38(), col, "");
        ds.addValue(loadData.getData39(), col, "");
        ds.addValue(loadData.getData40(), col, "10:00:00");
        ds.addValue(loadData.getData41(), col, "");
        ds.addValue(loadData.getData42(), col, "");
        ds.addValue(loadData.getData43(), col, "");
        ds.addValue(loadData.getData44(), col, "11:00:00");
        ds.addValue(loadData.getData45(), col, "");
        ds.addValue(loadData.getData46(), col, "");
        ds.addValue(loadData.getData47(), col, "");
        ds.addValue(loadData.getData48(), col, "12:00:00");
        ds.addValue(loadData.getData49(), col, "");
        ds.addValue(loadData.getData50(), col, "");
        ds.addValue(loadData.getData51(), col, "");
        ds.addValue(loadData.getData52(), col, "13:00:00");
        ds.addValue(loadData.getData53(), col, "");
        ds.addValue(loadData.getData54(), col, "");
        ds.addValue(loadData.getData55(), col, "");
        ds.addValue(loadData.getData56(), col, "14:00:00");
        ds.addValue(loadData.getData57(), col, "");
        ds.addValue(loadData.getData58(), col, "");
        ds.addValue(loadData.getData59(), col, "");
        ds.addValue(loadData.getData60(), col, "15:00:00");
        ds.addValue(loadData.getData61(), col, "");
        ds.addValue(loadData.getData62(), col, "");
        ds.addValue(loadData.getData63(), col, "");
        ds.addValue(loadData.getData64(), col, "16:00:00");
        ds.addValue(loadData.getData65(), col, "");
        ds.addValue(loadData.getData66(), col, "");
        ds.addValue(loadData.getData67(), col, "");
        ds.addValue(loadData.getData68(), col, "17:00:00");
        ds.addValue(loadData.getData69(), col, "");
        ds.addValue(loadData.getData70(), col, "");
        ds.addValue(loadData.getData71(), col, "");
        ds.addValue(loadData.getData72(), col, "18:00:00");
        ds.addValue(loadData.getData73(), col, "");
        ds.addValue(loadData.getData74(), col, "");
        ds.addValue(loadData.getData75(), col, "");
        ds.addValue(loadData.getData76(), col, "19:00:00");
        ds.addValue(loadData.getData77(), col, "");
        ds.addValue(loadData.getData78(), col, "");
        ds.addValue(loadData.getData79(), col, "");
        ds.addValue(loadData.getData80(), col, "20:00:00");
        ds.addValue(loadData.getData81(), col, "");
        ds.addValue(loadData.getData82(), col, "");
        ds.addValue(loadData.getData83(), col, "");
        ds.addValue(loadData.getData84(), col, "21:00:00");
        ds.addValue(loadData.getData85(), col, "");
        ds.addValue(loadData.getData86(), col, "");
        ds.addValue(loadData.getData87(), col, "");
        ds.addValue(loadData.getData88(), col, "22:00:00");
        ds.addValue(loadData.getData89(), col, "");
        ds.addValue(loadData.getData90(), col, "");
        ds.addValue(loadData.getData91(), col, "");
        ds.addValue(loadData.getData92(), col, "23:00:00");
        ds.addValue(loadData.getData93(), col, "");
        ds.addValue(loadData.getData94(), col, "");
        ds.addValue(loadData.getData95(), col, "");


        col = new String("上包络线");
        LoadData upr = loadData.multiple(1.1);
        ds.addValue(upr.getData00(), col, "00:00:00");
        ds.addValue(upr.getData01(), col, "");
        ds.addValue(upr.getData02(), col, "");
        ds.addValue(upr.getData03(), col, "");
        ds.addValue(upr.getData04(), col, "01:00:00");
        ds.addValue(upr.getData05(), col, "");
        ds.addValue(upr.getData06(), col, "");
        ds.addValue(upr.getData07(), col, "");
        ds.addValue(upr.getData08(), col, "02:00:00");
        ds.addValue(upr.getData09(), col, "");
        ds.addValue(upr.getData10(), col, "");
        ds.addValue(upr.getData11(), col, "");
        ds.addValue(upr.getData12(), col, "03:00:00");
        ds.addValue(upr.getData13(), col, "");
        ds.addValue(upr.getData14(), col, "");
        ds.addValue(upr.getData15(), col, "");
        ds.addValue(upr.getData16(), col, "04:00:00");
        ds.addValue(upr.getData17(), col, "");
        ds.addValue(upr.getData18(), col, "");
        ds.addValue(upr.getData19(), col, "");
        ds.addValue(upr.getData20(), col, "05:00:00");
        ds.addValue(upr.getData21(), col, "");
        ds.addValue(upr.getData22(), col, "");
        ds.addValue(upr.getData23(), col, "");
        ds.addValue(upr.getData24(), col, "06:00:00");
        ds.addValue(upr.getData25(), col, "");
        ds.addValue(upr.getData26(), col, "");
        ds.addValue(upr.getData27(), col, "");
        ds.addValue(upr.getData28(), col, "07:00:00");
        ds.addValue(upr.getData29(), col, "");
        ds.addValue(upr.getData30(), col, "");
        ds.addValue(upr.getData31(), col, "");
        ds.addValue(upr.getData32(), col, "08:00:00");
        ds.addValue(upr.getData33(), col, "");
        ds.addValue(upr.getData34(), col, "");
        ds.addValue(upr.getData35(), col, "");
        ds.addValue(upr.getData36(), col, "09:00:00");
        ds.addValue(upr.getData37(), col, "");
        ds.addValue(upr.getData38(), col, "");
        ds.addValue(upr.getData39(), col, "");
        ds.addValue(upr.getData40(), col, "10:00:00");
        ds.addValue(upr.getData41(), col, "");
        ds.addValue(upr.getData42(), col, "");
        ds.addValue(upr.getData43(), col, "");
        ds.addValue(upr.getData44(), col, "11:00:00");
        ds.addValue(upr.getData45(), col, "");
        ds.addValue(upr.getData46(), col, "");
        ds.addValue(upr.getData47(), col, "");
        ds.addValue(upr.getData48(), col, "12:00:00");
        ds.addValue(upr.getData49(), col, "");
        ds.addValue(upr.getData50(), col, "");
        ds.addValue(upr.getData51(), col, "");
        ds.addValue(upr.getData52(), col, "13:00:00");
        ds.addValue(upr.getData53(), col, "");
        ds.addValue(upr.getData54(), col, "");
        ds.addValue(upr.getData55(), col, "");
        ds.addValue(upr.getData56(), col, "14:00:00");
        ds.addValue(upr.getData57(), col, "");
        ds.addValue(upr.getData58(), col, "");
        ds.addValue(upr.getData59(), col, "");
        ds.addValue(upr.getData60(), col, "15:00:00");
        ds.addValue(upr.getData61(), col, "");
        ds.addValue(upr.getData62(), col, "");
        ds.addValue(upr.getData63(), col, "");
        ds.addValue(upr.getData64(), col, "16:00:00");
        ds.addValue(upr.getData65(), col, "");
        ds.addValue(upr.getData66(), col, "");
        ds.addValue(upr.getData67(), col, "");
        ds.addValue(upr.getData68(), col, "17:00:00");
        ds.addValue(upr.getData69(), col, "");
        ds.addValue(upr.getData70(), col, "");
        ds.addValue(upr.getData71(), col, "");
        ds.addValue(upr.getData72(), col, "18:00:00");
        ds.addValue(upr.getData73(), col, "");
        ds.addValue(upr.getData74(), col, "");
        ds.addValue(upr.getData75(), col, "");
        ds.addValue(upr.getData76(), col, "19:00:00");
        ds.addValue(upr.getData77(), col, "");
        ds.addValue(upr.getData78(), col, "");
        ds.addValue(upr.getData79(), col, "");
        ds.addValue(upr.getData80(), col, "20:00:00");
        ds.addValue(upr.getData81(), col, "");
        ds.addValue(upr.getData82(), col, "");
        ds.addValue(upr.getData83(), col, "");
        ds.addValue(upr.getData84(), col, "21:00:00");
        ds.addValue(upr.getData85(), col, "");
        ds.addValue(upr.getData86(), col, "");
        ds.addValue(upr.getData87(), col, "");
        ds.addValue(upr.getData88(), col, "22:00:00");
        ds.addValue(upr.getData89(), col, "");
        ds.addValue(upr.getData90(), col, "");
        ds.addValue(upr.getData91(), col, "");
        ds.addValue(upr.getData92(), col, "23:00:00");
        ds.addValue(upr.getData93(), col, "");
        ds.addValue(upr.getData94(), col, "");
        ds.addValue(upr.getData95(), col, "");
        JFreeChart chart = ChartFactory.createLineChart("负荷预测", "时刻", "全网耗电功率/MW", ds, PlotOrientation.VERTICAL, true, true, true);
        chart.setBorderVisible(true);

        LineAndShapeRenderer renderer = (LineAndShapeRenderer) chart.getCategoryPlot().getRenderer();
        renderer.setSeriesStroke(0, new BasicStroke(2));
        renderer.setSeriesStroke(1, new BasicStroke(2));
        renderer.setSeriesStroke(2, new BasicStroke(2));
        chart.getCategoryPlot().setRenderer(renderer);
        return chart;
    }
}
